# Configurations
title:            Nate Beatty
longtitle:        Nate's website and blog | Former CTO of IrisVR
author:           Nate Beatty
twitter_username: tnbeatty
github_username:  tnbeatty
# email:          donotemail@gmail.com  
description: >
  Useful, useless, and/or needless information.

version:          1.0
gitbook_version:  3.2.3

url:              'https://tnbeatty.github.io'
# baseurl:          '/'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: tnbeatty/tnbeatty.github.io

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: monokai_sublime

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
